name: Build macOS App
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./ZoomPen

      - name: Build macOS Application
        run: npx electron-builder --mac
        working-directory: ./ZoomPen
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZoomPen-macOS
          path: |
            ZoomPen/dist/*.dmg
            ZoomPen/dist/*.zip
